runv1:
	celery -A tasksv1 worker --loglevel=debug --without-gossip --without-mingle --without-heartbeat
runv2:
	celery -A tasksv2 worker --loglevel=debug --without-gossip --without-mingle --without-heartbeat

